# Generated by Django 5.0.2 on 2025-06-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المستأجر')),
                ('property_type', models.CharField(choices=[('commercial', 'محل تجاري'), ('residential', 'سكن'), ('company', 'شركة')], max_length=20, verbose_name='نوع العقار')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الايجار الشهري')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية العقد')),
                ('end_date', models.DateField(verbose_name='تاريخ نهاية العقد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
